import Head from 'next/head';
import { useState, useEffect, useRef } from 'react';

const MSGS=['文学的構造を解析中...','批評理論を適用中...','歴史的文脈を調査中...','登場人物の心理を分析中...','テーマと象徴を抽出中...','学術的視点を統合中...','レポートを編纂中...'];
const s={wrap:{maxWidth:680,margin:'0 auto',padding:'2rem 1.5rem 5rem'},sec:{background:'var(--bg2)',borderRadius:12,padding:'1rem 1.25rem',marginBottom:'1rem'}};
const Sec=({label,children})=><div style={s.sec}><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'0.12em',color:'var(--text3)',marginBottom:8}}>{label}</div><div style={{fontSize:14,lineHeight:1.8,color:'var(--text)'}}>{children}</div></div>;
const Div=({label})=><div style={{display:'flex',alignItems:'center',gap:10,margin:'0.8rem 0'}}><div style={{flex:1,height:'0.5px',background:'var(--border)'}}></div>{label&&<span style={{fontSize:12,color:'var(--text3)'}}>{label}</span>}<div style={{flex:1,height:'0.5px',background:'var(--border)'}}></div></div>;
const Bdg=({c})=><span style={{fontSize:12,padding:'3px 10px',borderRadius:99,border:'0.5px solid var(--border2)',color:'var(--text2)',background:'var(--bg2)'}}>{c}</span>;
function Tabs({tabs,active,onSwitch}){return<div style={{display:'flex',gap:2,flexWrap:'wrap',borderBottom:'0.5px solid var(--border)',marginBottom:'1.2rem'}}>{tabs.map((t,i)=><button key={i} onClick={()=>onSwitch(i)} style={{fontSize:12,padding:'8px 11px 10px',cursor:'pointer',color:active===i?'var(--text)':'var(--text2)',border:'none',background:'transparent',borderBottom:active===i?'2px solid var(--amber)':'2px solid transparent',marginBottom:'-0.5px',fontFamily:'inherit',fontWeight:active===i?500:400}}>{t}</button>)}</div>;}
function AffBox({title,author,cfg,onClickLink}){
  const q=encodeURIComponent((title+' '+author).trim()),tag=cfg.amzTag,rak=cfg.rakTag;
    const amz=`https://www.amazon.co.jp/s?k=${q}${tag?'&tag='+encodeURIComponent(tag):''}`;
      const kindle=`https://www.amazon.co.jp/s?k=${q}+kindle${tag?'&tag='+encodeURIComponent(tag):''}`;
        const aud=`https://www.audible.co.jp/search?keywords=${q}`;
          const rakUrl=rak?`https://hb.afl.rakuten.co.jp/hgc/${rak}/?pc=https%3A%2F%2Fbooks.rakuten.co.jp%2Fsearch%3Fsitem%3D${q}`:`https://books.rakuten.co.jp/search?sitem=${q}`;
            const btn=(href,bg,color,label)=><a href={href} target="_blank" rel="noopener noreferrer" onClick={onClickLink} style={{display:'flex',alignItems:'center',justifyContent:'center',gap:6,padding:'11px 14px',borderRadius:8,cursor:'pointer',fontSize:14,textDecoration:'none',background:bg,color,fontWeight:500}}>{label}</a>;
              return<div style={{background:'var(--bg2)',border:'0.5px solid var(--border2)',borderRadius:12,padding:'1.1rem 1.25rem',marginBottom:'1.2rem'}}>
                  <div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'0.12em',color:'var(--text3)',marginBottom:10}}>この本を購入する</div>
                      {!tag&&!rak&&<p style={{fontSize:12,color:'var(--warn)',textAlign:'center',paddingBottom:8,fontStyle:'italic'}}>⚠ アフィリエイトIDが未設定です</p>}
                          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{btn(amz,'#FF9900','#111','📦 Amazon で購入')}{btn(rakUrl,'#BF0000','#fff','🛒 楽天ブックス')}{btn(kindle,'#00A8E1','#fff','📱 Kindle 版')}{btn(aud,'#F55D1E','#fff','🎧 Audible')}</div>
                              <p style={{fontSize:11,color:'var(--text3)',marginTop:8,textAlign:'center'}}>{tag?`✓ アフィリエイトリンク有効（${tag}）`:'アフィリエイトIDを設定してください'}</p>
                                </div>;
                                }
                                export default function Home(){
                                  const[title,setTitle]=useState('');const[author,setAuthor]=useState('');const[focus,setFocus]=useState('');
                                    const[loading,setLoading]=useState(false);const[loadMsg,setLoadMsg]=useState('');
                                      const[result,setResult]=useState(null);const[error,setError]=useState('');const[tab,setTab]=useState(0);
                                        const[showSetup,setShowSetup]=useState(false);const[cfg,setCfg]=useState({amzTag:'',rakTag:''});
                                          const[amzInput,setAmzInput]=useState('');const[rakInput,setRakInput]=useState('');
                                            const[stats,setStats]=useState({searches:0,clicks:0});const liRef=useRef(null);
                                              useEffect(()=>{const s=localStorage.getItem('aff-cfg');if(s){const c=JSON.parse(s);setCfg(c);setAmzInput(c.amzTag||'');setRakInput(c.rakTag||'');}const st=localStorage.getItem('aff-stats');if(st)setStats(JSON.parse(st));},[]);
                                                const saveSettings=()=>{const c={amzTag:amzInput.trim(),rakTag:rakInput.trim()};setCfg(c);localStorage.setItem('aff-cfg',JSON.stringify(c));setShowSetup(false);};
                                                  const trackClick=()=>{const ns={...stats,clicks:stats.clicks+1};setStats(ns);localStorage.setItem('aff-stats',JSON.stringify(ns));};
                                                    const ctr=stats.searches>0?Math.round((stats.clicks/stats.searches)*100):0;
                                                      const generate=async()=>{
                                                          if(!title)return;setError('');setResult(null);setLoading(true);setTab(0);
                                                              let i=0;setLoadMsg(MSGS[0]);liRef.current=setInterval(()=>{i=(i+1)%MSGS.length;setLoadMsg(MSGS[i]);},2200);
                                                                  const ns={...stats,searches:stats.searches+1};setStats(ns);localStorage.setItem('aff-stats',JSON.stringify(ns));
                                                                      try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,author,focus})});
                                                                            const d=await res.json();clearInterval(liRef.current);setLoading(false);
                                                                                  if(!d.found){setError('作品が見つかりませんでした。');return;}setResult(d);
                                                                                      }catch(e){clearInterval(liRef.current);setLoading(false);setError('エラーが発生しました。');}
                                                                                        };
                                                                                          const reset=()=>{setResult(null);setTitle('');setAuthor('');setFocus('');setTab(0);};
                                                                                            const d=result;
                                                                                              const lbl=(t)=><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'0.1em',color:'var(--text2)',marginBottom:5}}>{t}</div>;
                                                                                                return<>
                                                                                                    <Head><title>書籍まるわかり</title><meta name="description" content="論文レベルの書籍分析"/><meta name="viewport" content="width=device-width,initial-scale=1"/></Head>
                                                                                                        <div style={s.wrap}>
                                                                                                              <div style={{marginBottom:'1.8rem',textAlign:'center'}}>
                                                                                                                      <p style={{fontSize:11,letterSpacing:'0.15em',textTransform:'uppercase',color:'var(--text3)',marginBottom:4}}>Academic Book Intelligence</p>
                                                                                                                              <h1 style={{fontFamily:"'Playfair Display',serif",fontSize:28,fontWeight:700,color:'var(--text)',lineHeight:1.2}}>書籍まるわかり</h1>
                                                                                                                                      <p style={{fontSize:13,color:'var(--text2)',marginTop:4,fontStyle:'italic'}}>タイトルを入れるだけで論文が書けるレベルの分析を生成</p>
                                                                                                                                            </div>
                                                                                                                                                  {showSetup&&<div style={{background:'var(--bg2)',border:'0.5px solid var(--border2)',borderRadius:12,padding:'1rem 1.25rem',marginBottom:'1.2rem'}}>
                                                                                                                                                          <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}>
                                                                                                                                                                    <span style={{fontSize:12,textTransform:'uppercase',letterSpacing:'0.1em',color:'var(--text3)'}}>アフィリエイト設定</span>
                                                                                                                                                                              <button onClick={()=>setShowSetup(false)} style={{fontSize:12,color:'var(--text3)',background:'none',border:'none',cursor:'pointer',textDecoration:'underline',fontFamily:'inherit'}}>閉じる</button>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              <div style={{marginBottom:8}}>{lbl('Amazon アソシエイトID')}<div style={{display:'flex',gap:8}}><input value={amzInput} onChange={e=>setAmzInput(e.target.value)} placeholder="例: yourtag-22" style={{flex:1,fontSize:14}}/><button onClick={saveSettings} style={{padding:'7px 16px',fontSize:13,cursor:'pointer',background:'var(--text)',color:'var(--bg)',border:'none',borderRadius:8,fontFamily:'inherit',whiteSpace:'nowrap'}}>保存</button></div></div>
                                                                                                                                                                                                      <div>{lbl('楽天アフィリエイトID（任意）')}<input value={rakInput} onChange={e=>setRakInput(e.target.value)} placeholder="例: xxxxxxxx.xxxxxxxx" style={{fontSize:14}}/></div>
                                                                                                                                                                                                              <p style={{fontSize:12,color:'var(--text3)',lineHeight:1.6,marginTop:8}}><a href="https://affiliate.amazon.co.jp/" target="_blank" rel="noopener noreferrer">Amazon登録 →</a><a href="https://affiliate.rakuten.co.jp/" target="_blank" rel="noopener noreferrer" style={{marginLeft:8}}>楽天登録 →</a></p>
                                                                                                                                                                                                                    </div>}
                                                                                                                                                                                                                          <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginBottom:'0.8rem'}}>
                                                                                                                                                                                                                                  {[['検索回数',stats.searches],['リンクClick',stats.clicks],['CTR',ctr+'%']].map(([l,v])=><div key={l} style={{background:'var(--bg2)',borderRadius:8,padding:'0.7rem 1rem',textAlign:'center'}}><div style={{fontFamily:"'Playfair Display',serif",fontSize:22,fontWeight:700,color:'var(--text)'}}>{v}</div><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'0.08em',color:'var(--text3)',marginTop:2}}>{l}</div></div>)}
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                              <div style={{textAlign:'right',marginBottom:'1.2rem'}}><button onClick={()=>setShowSetup(v=>!v)} style={{fontSize:12,color:'var(--text3)',background:'none',border:'none',cursor:'pointer',textDecoration:'underline',fontFamily:'inherit'}}>⚙ アフィリエイト設定{cfg.amzTag?' ✓':''}</button></div>
                                                                                                                                                                                                                                                    {!result&&!loading&&<div>
                                                                                                                                                                                                                                                            <div style={{marginBottom:'0.9rem'}}>{lbl('本のタイトル')}<input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&generate()} placeholder="例：人間失格"/></div>
                                                                                                                                                                                                                                                                    <div style={{marginBottom:'0.9rem'}}>{lbl('著者名')}<input value={author} onChange={e=>setAuthor(e.target.value)} onKeyDown={e=>e.key==='Enter'&&generate()} placeholder="例：太宰治"/></div>
                                                                                                                                                                                                                                                                            <div style={{marginBottom:'0.9rem'}}>{lbl('論文の焦点（任意）')}<textarea value={focus} onChange={e=>setFocus(e.target.value)} placeholder="例：フェミニズム批評の観点から考察したい" style={{width:'100%',fontFamily:'inherit',fontSize:14,resize:'vertical',minHeight:56,padding:'8px 12px',border:'0.5px solid var(--border2)',borderRadius:8,color:'var(--text)',background:'var(--bg)',lineHeight:1.6}}/></div>
                                                                                                                                                                                                                                                                                    <button onClick={generate} style={{width:'100%',padding:12,fontFamily:"'Playfair Display',serif",fontSize:16,fontWeight:500,cursor:'pointer',background:'var(--text)',color:'var(--bg)',border:'none',borderRadius:8,letterSpacing:'0.03em'}}>学術分析を開始する →</button>
                                                                                                                                                                                                                                                                                            {error&&<p style={{fontSize:14,color:'var(--danger)',textAlign:'center',padding:'0.8rem',fontStyle:'italic'}}>{error}</p>}
                                                                                                                                                                                                                                                                                                  </div>}
                                                                                                                                                                                                                                                                                                        {loading&&<div style={{textAlign:'center',padding:'3rem 1rem'}}><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style><div style={{width:28,height:28,border:'1.5px solid var(--border)',borderTopColor:'var(--amber)',borderRadius:'50%',animation:'spin .8s linear infinite',margin:'0 auto 1rem'}}/><p style={{fontSize:13,color:'var(--text2)',fontStyle:'italic'}}>{loadMsg}</p></div>}
                                                                                                                                                                                                                                                                                                              {d&&<div>
                                                                                                                                                                                                                                                                                                                      <div style={{marginBottom:'1.5rem',paddingBottom:'1.5rem',borderBottom:'0.5px solid var(--border)'}}>
                                                                                                                                                                                                                                                                                                                                <div style={{fontFamily:"'Playfair Display',serif",fontSize:24,fontWeight:700,color:'var(--text)',fontStyle:'italic'}}>『{title}』</div>
                                                                                                                                                                                                                                                                                                                                          <div style={{fontSize:15,color:'var(--text2)',marginTop:4}}>{author}{d.year?' · '+d.year:''}</div>
                                                                                                                                                                                                                                                                                                                                                    <div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:8}}>{[d.period,d.country,d.year,d.genre].filter(Boolean).map((b,i)=><Bdg key={i} c={b}/>)}</div>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                    <AffBox title={title} author={author} cfg={cfg} onClickLink={trackClick}/>
                                                                                                                                                                                                                                                                                                                                                                            <Tabs tabs={['概要','構造','人物','テーマ・技法','批評理論','論文執筆']} active={tab} onSwitch={setTab}/>
                                                                                                                                                                                                                                                                                                                                                                                    {tab===0&&<><Sec label="詳細あらすじ">{d.overview}</Sec><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1rem',marginBottom:'1rem'}}><div style={{background:'var(--bg2)',borderRadius:8,padding:'0.9rem 1.1rem'}}><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'.1em',color:'var(--text3)',marginBottom:4}}>文学運動</div><div style={{fontSize:14,fontWeight:500,color:'var(--text)'}}>{d.period||'—'}</div></div><div style={{background:'var(--bg2)',borderRadius:8,padding:'0.9rem 1.1rem'}}><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'.1em',color:'var(--text3)',marginBottom:4}}>出版年・地域</div><div style={{fontSize:14,fontWeight:500,color:'var(--text)'}}>{d.year||'—'}{d.country?' / '+d.country:''}</div></div></div><Sec label="著者について">{d.authorBio}</Sec><Sec label="歴史的・社会的文脈">{d.historicalContext}</Sec><Sec label="受容史・評価の変遷">{d.reception}</Sec><Sec label="キーワード"><div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:4}}>{(d.keywords||[]).map((k,i)=><Bdg key={i} c={k}/>)}</div></Sec></>}
                                                                                                                                                                                                                                                                                                                                                                                            {tab===1&&<><Sec label="形式・語りの構造">{d.structure?.overview}</Sec><div style={s.sec}><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'.12em',color:'var(--text3)',marginBottom:10}}>物語の展開</div>{(d.structure?.acts||[]).map((a,i)=><div key={i} style={{padding:'0.9rem 0',borderBottom:i<(d.structure.acts.length-1)?'0.5px solid var(--border)':'none'}}><div style={{fontSize:10,letterSpacing:'.1em',textTransform:'uppercase',color:'var(--text3)',marginBottom:3}}>{a.label}</div><div style={{fontSize:14,fontWeight:500,color:'var(--text)',marginBottom:4}}>{a.title}</div><div style={{fontSize:13,lineHeight:1.7,color:'var(--text2)'}}>{a.summary}</div><div style={{fontSize:12,color:'var(--text3)',marginTop:4}}>▸ {a.significance}</div></div>)}</div></>}
                                                                                                                                                                                                                                                                                                                                                                                                    {tab===2&&<div style={s.sec}><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'.12em',color:'var(--text3)',marginBottom:6}}>登場人物分析</div>{(d.characters||[]).map((c,i)=><div key={i} style={{display:'flex',gap:12,alignItems:'flex-start',padding:'0.8rem 0',borderBottom:i<(d.characters.length-1)?'0.5px solid var(--border)':'none'}}><div style={{width:36,height:36,flexShrink:0,borderRadius:'50%',background:'var(--bg)',border:'0.5px solid var(--border2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:500,color:'var(--text2)'}}>{c.initials||c.name.slice(0,2)}</div><div><div style={{fontSize:14,fontWeight:500,color:'var(--text)',marginBottom:2}}>{c.name}</div><div style={{fontSize:12,color:'var(--text3)',marginBottom:4}}>{c.role}</div><div style={{fontSize:13,lineHeight:1.65,color:'var(--text2)'}}>{c.description}</div>{c.academicNote&&<div style={{fontSize:12,color:'var(--text3)',marginTop:4,fontStyle:'italic'}}>⌑ {c.academicNote}</div>}</div></div>)}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                            {tab===3&&<><div style={s.sec}><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'.12em',color:'var(--text3)',marginBottom:6}}>主要テーマ</div>{(d.themes||[]).map((t,i)=><div key={i} style={{padding:'0.8rem 0',borderBottom:i<(d.themes.length-1)?'0.5px solid var(--border)':'none'}}><div style={{fontSize:14,fontWeight:500,color:'var(--text)',marginBottom:4}}>{t.name}</div><div style={{fontSize:13,lineHeight:1.7,color:'var(--text2)'}}>{t.analysis}</div></div>)}</div><Div label="文学技法"/><div style={s.sec}>{(d.literaryTechniques||[]).map((t,i)=><div key={i} style={{padding:'0.8rem 0',borderBottom:i<(d.literaryTechniques.length-1)?'0.5px solid var(--border)':'none'}}><div style={{fontSize:14,fontWeight:500,color:'var(--text)',marginBottom:4}}>{t.technique}</div><div style={{fontSize:13,lineHeight:1.7,color:'var(--text2)'}}>{t.usage}</div></div>)}</div><Div label="象徴・モチーフ"/><div style={s.sec}>{(d.symbolism||[]).map((sym,i)=><div key={i} style={{padding:'0.8rem 0',borderBottom:i<(d.symbolism.length-1)?'0.5px solid var(--border)':'none'}}><div style={{fontSize:14,fontWeight:500,color:'var(--text)',marginBottom:4}}>{sym.symbol}</div><div style={{fontSize:13,lineHeight:1.7,color:'var(--text2)'}}>{sym.meaning}</div></div>)}</div><Div label="印象的な箇所"/>{(d.quotablePassages||[]).map((q,i)=><div key={i} style={{borderLeft:'2px solid var(--border2)',padding:'0.8rem 1rem',marginBottom:'0.8rem',background:'var(--bg2)',borderRadius:'0 8px 8px 0'}}><div style={{fontSize:14,fontStyle:'italic',lineHeight:1.8,color:'var(--text)'}}>{q.text}</div><div style={{fontSize:12,color:'var(--text3)',marginTop:6}}>{q.analysis}</div></div>)}</>}
                                                                                                                                                                                                                                                                                                                                                                                                                    {tab===4&&<><div style={{marginBottom:'1rem'}}>{(d.criticalPerspectives||[]).map((c,i)=><div key={i} style={{padding:'0.8rem 1rem',background:'var(--bg2)',borderRadius:8,marginBottom:8}}><div style={{fontSize:11,textTransform:'uppercase',letterSpacing:'.1em',color:'var(--text3)',marginBottom:4}}>{c.school}</div><div style={{fontSize:13,lineHeight:1.7,color:'var(--text)'}}>{c.analysis}</div></div>)}</div><Sec label="比較文学的位置づけ">{d.comparativeLiterature}</Sec></>}
                                                                                                                                                                                                                                                                                                                                                                                                                            {tab===5&&<><div>{(d.thesisIdeas||[]).map((t,i)=><div key={i} style={{border:'0.5px solid var(--border2)',borderRadius:12,padding:'1rem 1.25rem',marginBottom:'0.9rem'}}><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'.12em',color:'var(--text3)',marginBottom:6}}>論文テーマ案 {i+1}</div><div style={{fontSize:14,lineHeight:1.8,color:'var(--text)',fontStyle:'italic'}}>{t}</div></div>)}</div><Div label="参考文献"/><div style={s.sec}>{(d.suggestedReferences||[]).map((r,i)=><div key={i} style={{fontSize:13,lineHeight:1.7,color:'var(--text2)',padding:'0.5rem 0',borderBottom:i<(d.suggestedReferences.length-1)?'0.5px solid var(--border)':'none'}}>{r}</div>)}</div></>}
                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={reset} style={{display:'block',width:'100%',marginTop:'2rem',padding:10,fontSize:14,cursor:'pointer',background:'transparent',border:'0.5px solid var(--border2)',borderRadius:8,color:'var(--text2)',fontFamily:'inherit'}}>← 別の作品を分析する</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
